# coding: utf-8

"""
    Personal Knowledge Graph System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.link_create import LinkCreate

class TestLinkCreate(unittest.TestCase):
    """LinkCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkCreate:
        """Test LinkCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkCreate`
        """
        model = LinkCreate()
        if include_optional:
            return LinkCreate(
                target_id = 56
            )
        else:
            return LinkCreate(
                target_id = 56,
        )
        """

    def testLinkCreate(self):
        """Test LinkCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
